.streamlit/secrets.toml
Google Service Account for Google Sheets
[gcp_sheets_service_account]
type = "service_account"
project_id = "garminuserdata"
private_key_id = "10a26d3d3dd8afaf31500fb43f2751e26f927745"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDIIlS7KGHnBj4A
K+or/Euv5b+Shat4O2Jf3sGT29vQBnNt78Vr1kiggisBo32QTNPyG5nf1EYW17/0
fF6eYsOfxH30RKeH0QIx0OxoFU5oeeOYnXQhplBIAgsG73tpUZdoUircpK1sieNL
NhXdwhv0k62wzChABC619diWSzAzTmQbsH6OhxhQCWxECOKQP8BDX2Y/tO4Mx0QT
ywcT3HU7i3ML/QQC6z0aBYJkpvxA4+0hjCV5MhPcB+S+ncG06+lzPcylTxgYb/vz
AWvnskuvNbZAKfermDzIV41SseexHIc+ak49/46hPa+odckuqQc8xh21Cv0kN3Ym
7/r3Rz1NAgMBAAECgf8uUcPKjU4bahZvc7p+86WQ0FvGTamh6hyak7O5xOja/KM6
joPisXWdsILDnlMxUpa7Migq5bZTExwaOa6sea9NCu0b28fqZzVa0j/k1wmOpKdI
ayi1oQhzogVrVYH6niesvVeuOW7p7//rKFlnOcW+lW9du+KU7mLhOkUmg8BkHxda
4DY2ghNN8AfK6TFTRiDKzsngNkYew8WVz555LAG2srAt/Nw62bfAmWMqG8zSKRBU
PTKfULbHBzgKZGKrhyC3DVrAylGJDeF+pwld3/RnTOASAAGftgATNnEZjdZ42lt/
15/OLkUa1VkRwJ24kHrJC2bHxfl04P/xh2wbl3ECgYEA93zIX16tSeku9My9/Qlz
yOkN9d443epdla+d93gOuN7xgnVIatPqenLwFlZhGdieUYrn+tqaPNSsxpWbvtSN
3faBysXa653mMIeKQN8mn0h+uWRLXxNRiT0gWA6fhNj59ylCtMfqZEiCf7xNbn4U
ldsMEmu9yN7kpBHQczFYv9ECgYEAzwSVvZaY1JzON9JHuDgWswQuhkVl0AykehyG
6aeCNdXGppXx/tv/6AOwXN/X3DsTVoDPQeboetBNF2HG6+yfuoFbkmByyMazM/wQ
aq4xtgATwgI21rWVBGamZIX65FoC5PlJoXbs36lMIkzwduOl8Gku+a4VA8AEKC7s
QyGvoL0CgYEAh90e+ww0waCbwJQtsJ3hzGf03Ac03M7utWAFrndgTalGmEHekZbo
4HP8zaZ6BABhWY6SL6qWhdKTTymOqMJnZ2kOc80Ok87JMdcW1Oosf8ECoLAomHc4
icje2ricZgffogoqrqgZSxhrW8h6EbBxiJsKE4rGU2HZzyBgePycJiECgYEAtTN6
LhxnYZJvHoU8qY7Or5r1binIWDb4sLnPjS1F2AFqg92zmDTQ5jB0apazxt0erBTL
VQ/cZcN19wVqrI7NsN4RXSp2zi6+JL55UCdw87FVmfd+MKl36gY/lrV/SelPp0Rc
oqwa4iu5rDxULnxMfwZSS9GIK2QjP1jzDD+sDrECgYAUL3IzOibBsWbJ0sRnbiyL
lrToOnkkrdYiaFjWLmXv/m7sa9GAcV5e5eLvQkx4vZDKXjSNp4u2A6vOdQloYcyh
DGTiFcLz0rgRSu+CroA4BfRrz8FGsAs3EdyllOquhp0RySZBlaD6SUrS4KB1y8nP
6v5uudzlUKngo44IRiB2Og==
-----END PRIVATE KEY-----"""
client_email = "garmin-app-writer@garminuserdata.iam.gserviceaccount.com"
client_id = "100997487695992770007"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/garmin-app-writer%40garminuserdata.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

Google Service Account for BigQuery
[gcp_bigquery_service_account]
type = "service_account"
project_id = "garminuserdata"
private_key_id = "48134d3b1bf58a88741f204515597a840c613fd2"
private_key = """-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDNGwy5lYUcEXYI\nEk4i027RS6SZVDNOorkReZgm+21RPfJmv/rejXsId6c6K0yYEMejNZlbc6kKAr/b\nthe74Mu2XrA834djZ1BtdfJwwyAg1WOq/eF5QUlJK5BgdcLPrZvTJRMqFSOjcJos\nkN3ZhXvgj5nqU3cfDNesh616uSD+r46HlUM3RIWDwR1DM24jpbrfyzurtwNiwTlu\nS0z/naj4/BQSbCuBInHn/rbQeVIkhV4X61L0zZkyR6cn04/FAsB02QH65stEhUe1\nrooHDlgWf/hjsS2NV+P+d3XSvU7xbayeeINukPTnhdQd77MnZ3NjbifYmXq/kiDz\nrpUA0iNDAgMBAAECggEAB5s8YmRz9neECPr1iTmlM6JjJ08XRL6or6UhOMMOGFhl\nI8XRmuzwGq3Uk7pQoDq3E+iy3hZfWdeZiJ9ltEuMizdS198Vk3gRHoJ16Vnr4+vU\niN431ILn81JFF3AmlI/V8gN5VmGOfuJgyynEjwKsMJg87pLuwHR97O0/6017k62b\nRDEvgbXqQF7VWDeqG5CdEvzoVkUHoZtPjADn0jyyBrzk7vxs8NdB4Fmp4XAufsv9\nY6d7LitPLO1uB5r5EAgbvQ47wZ/uG6F0IYd6dYK0IMgCNui8RqBgelo0S0rpjFqS\nQlJ9AWAR1fAlKX/Dq0Sj4dOefO4lvtUV+oAdewIoOQKBgQD5f1kf3fcgVomAnvZX\nHC0gA8gFyc2grVx9rbO+ybyWNabpH5Kb8dRxSYEmNbJLoTVFGGmSjdC6h4lWZJaa\nMQ0QUbab28fKoVHu9L+4ODbQniv4pQyBgFzVi1MZahVzvYv3aLGLZLtTPXLLCFpm\n15LnV5dSTxGqGxYD+ZaUJ9wlZwKBgQDSc4TH0X863H8pOSBldWPHKzQbW+Ix/RTe\nEP9VbCpf23ihr/mszc1RnvhHYUBG5o8wnrP2rK8SNylJmLQh1dSZrNKqKRzUCv80\nZb0w8P1yoXC50G4ezaCw/jiGnOzw2n3gZaSRbEgQlfBtxPwVInU3kfoYnOlO6B1s\nFckkTU/txQKBgAXxU5Ufu1go14OZxbJTeHuvu17v7JbsKizQK1za/0PwqTYaS2qt\neurr3kijtMh6YYNwzmrwN82JlurY4IFxs6b0202hEYQxDXuMlthzdlLHwbJddAvN\nm+h2Nhd/4FzuYdwVwUzZrGCSMR7G5yhV8CjUfEU4nuoXVRHpKv4CaQr3AoGBAMz+\nAx+UPEc8koy3/Yt4cPOHbNkddkZVC+eHTP+LPfdjU6zDOgON7+oKXDNDUpX9bQrh\n+9BSwrGOk6QBn6y5mb4bLpTbOR5+m7oRQ+kRRP9Mq/4DPdC5YUYmSy8sWkv9t9FF\nkLiqbcPiGXEDCL0ZdG4tvhwNc+ENjeNDkUrQGAQ1AoGADJVtUtIKFCjEKHpAISNy\n2jwdcAGeFfe/wFGfOhntZQzTErOFOf+dEJpLW/Zyg/8GbrFPgQCrbk0BNsHM8fTQ\nIbWIRxHYgfOIObDgO89KJKkt/09ztvph5/DR3AtQhQwD6IQgU3gyMreYzj+g5Ebf\nE7Xv3IcmI9bLBFiODki7KVQ=\n-----END PRIVATE KEY-----\n"""
client_email = "garminuserdata@garminuserdata.iam.gserviceaccount.com"
client_id = "106768300223415646530"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/garminuserdata%40garminuserdata.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

Gemini API Key for LLM
gemini_api_key = "AIzaSyAiaswXxN3ngfEwMRXckBmEoZHO151jRv0"