[gcp_service_account]
type = "service_account"
project_id = "garminuserdata"
private_key_id = "10a26d3d3dd8afaf31500fb43f2751e26f927745"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDIIlS7KGHnBj4A
K+or/Euv5b+Shat4O2Jf3sGT29vQBnNt78Vr1kiggisBo32QTNPyG5nf1EYW17/0
fF6eYsOfxH30RKeH0QIx0OxoFU5oeeOYnXQhplBIAgsG73tpUZdoUircpK1sieNL
NhXdwhv0k62wzChABC619diWSzAzTmQbsH6OhxhQCWxECOKQP8BDX2Y/tO4Mx0QT
ywcT3HU7i3ML/QQC6z0aBYJkpvxA4+0hjCV5MhPcB+S+ncG06+lzPcylTxgYb/vz
AWvnskuvNbZAKfermDzIV41SseexHIc+ak49/46hPa+odckuqQc8xh21Cv0kN3Ym
7/r3Rz1NAgMBAAECgf8uUcPKjU4bahZvc7p+86WQ0FvGTamh6hyak7O5xOja/KM6
joPisXWdsILDnlMxUpa7Migq5bZTExwaOa6sea9NCu0b28fqZzVa0j/k1wmOpKdI
ayi1oQhzogVrVYH6niesvVeuOW7p7//rKFlnOcW+lW9du+KU7mLhOkUmg8BkHxda
4DY2ghNN8AfK6TFTRiDKzsngNkYew8WVz555LAG2srAt/Nw62bfAmWMqG8zSKRBU
PTKfULbHBzgKZGKrhyC3DVrAylGJDeF+pwld3/RnTOASAAGftgATNnEZjdZ42lt/
15/OLkUa1VkRwJ24kHrJC2bHxfl04P/xh2wbl3ECgYEA93zIX16tSeku9My9/Qlz
yOkN9d443epdla+d93gOuN7xgnVIatPqenLwFlZhGdieUYrn+tqaPNSsxpWbvtSN
3faBysXa653mMIeKQN8mn0h+uWRLXxNRiT0gWA6fhNj59ylCtMfqZEiCf7xNbn4U
ldsMEmu9yN7kpBHQczFYv9ECgYEAzwSVvZaY1JzON9JHuDgWswQuhkVl0AykehyG
6aeCNdXGppXx/tv/6AOwXN/X3DsTVoDPQeboetBNF2HG6+yfuoFbkmByyMazM/wQ
aq4xtgATwgI21rWVBGamZIX65FoC5PlJoXbs36lMIkzwduOl8Gku+a4VA8AEKC7s
QyGvoL0CgYEAh90e+ww0waCbwJQtsJ3hzGf03Ac03M7utWAFrndgTalGmEHekZbo
4HP8zaZ6BABhWY6SL6qWhdKTTymOqMJzZ2kOc80Ok87JMdcW1Oosf8ECoLAomHc4
icje2ricZgffogoqrqgZSxhrW8h6EbBxiJsKE4rGU2HZzyBgePycJiECgYEAtTN6
LhxnYZJvHoU8qY7Or5r1binIWDb4sLnPjS1F2AFqg92zmDTQ5jB0apazxt0erBTL
VQ/cZcN19wVqrI7NsN4RXSp2zi6+JL55UCdw87FVmfd+MKl36gY/lrV/SelPp0Rc
oqwa4iu5rDxULnxMfwZSS9GIK2QjP1jzDD+sDrECgYAUL3IzOibBsWbJ0sRnbiyL
lrToOnkkrdYiaFjWLmXv/m7sa9GAcV5e5eLvQkx4vZDKXjSNp4u2A6vOdQloYcyh
DGTiFcLz0rgRSu+CroA4BfRrz8FGsAs3EdyllOquhp0RySZBlaD6SUrS4KB1y8nP
6v5uudzlUKngo44IRiB2Og==
-----END PRIVATE KEY-----"""
client_email = "garmin-app-writer@garminuserdata.iam.gserviceaccount.com"
client_id = "100997487695992770007"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/garmin-app-writer%40garminuserdata.iam.gserviceaccount.com"
universe_domain = "googleapis.com"