[gcp_service_account]
type = "service_account"
project_id = "garminuserdata"
private_key_id = "ba670364592c707a4d301df96eaedc09d57c62bc"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDCe7kPNnClDQmL
XoXLhWvBaJIMgbRSWEcq1liaOFb402fy9rGsZMMM29l0Lez8UeIUkr7fgCb2jUji
vD2uVFSP+C7oWgh7Ee10cOOImUjetox8ZZPe/Q/x/0XxDsrWjrthUZRUxboB2S1D
Pj+5MN6N3+SKq31dt+qBPUYqFy2LdHUVJnaTn7wBOzl0d+nokTsu3k/QtYxMfZ3j
HoktRwHgEIb16M1eRlioHVLf8yAb8SZhFrqK1SU94FfkY+v2k6GK9PqLL/kr74wX
NJ3i3FMjN6UG+4dU3HrcuyXNZQIeDbVYlHOy7wpDieNgcSz8+XbgKmJNAXp0pXGq
r1h3wIqbAgMBAAECggEAEYa4zKgpSpZ8L7Ua9ZZWeZ2E29+scmdGMpQSdANzwwS6
L2kP5etGsJf3ZsLkwnBWoWgAD4ArArkEwnoYTOeIn1jMUWAbt4uMDJxHxP2bVYa5
7lPxGX1QvIw2r1yX5vIB7Ok/JsyS0KvTqmWntHa097AflmeR6qoyVedBtXVVQ2XZ
EY8tHsqgqaYlxIJ232UevSBhwBNeGP+k5KiCxcHrRe8iIOhb1wzjLkEwFW0gY/i1
L1jztl2UpeCoC7xfZ1WkEaPyiJutar7stSSea8Fmt3z8Trsvdp5qZMeL5SCC7c3A
Ifh/+cRdW0V6FJO7wjgcuuIQHAFbS1KRzWPWKjBdsQKBgQDnEhEPLMnBchtnUjoj
906mj37f+ZWBbHOH1BRuUXeQuw6k/m3RR9OPKhUZuRFbXoR065mfidhMHCQASl5k
y7Lc9tbeF99+ie7oGamQsnbR3cc9PBQHvRxqdVAtUn/kH5U4VTBW2hS+UZcj4UrQ
ZaNehAva/B2GtP6JLsvo7YkD1QKBgQDXdyclbk1gaNu04+ZqOpn1tNLfOBWhygfs
bwhlUKP3AKp+tANnnFrv2N5sXCUMj0HRRbc6wzURKHDshUjAT1RwsT7JSgpCAUL7
uCHp466m8YjcfduGy/GblCc8Pl3gQYpZe1g8/4Cb4/RsW3Dm3bxDZwIM/cbEeOrp
hqdgtu08rwKBgFEufsHXGXcWUNxm/jg+nepUxd2IwWb8JEbXUupDQv+dSJLdNNXv
JzvILCuiYp+4QE8XqxxrAIwU4u0bM7iz/D43ltvmhUXezgnLYlCM8sPe6C3yWpMx
dLdOSgHyVy5djj6BZ39MFTecUL5xW6iF3PTK7aNdKj52fmrR/x/xvE6VAoGAI+os
kESuiR9xX9mNEq/p8dbOP37tvCYc5AAt+hVS/10RDkWbO64ISmpvyMgjNNC8O9HP
FPBs7As9p28gDU4r2QzyVkMNKqtjKuoqXP4iopkoIvinmvRrtW8gix4qL7M9CGVS
8/fyzAlXOKiVTSYwt1t4MAotE5rELWDQjYJwUOkCgYEApxnwLbpzAH20kGeRm6Uz
rlFbn8i2D7mdnrDLE2UWROfJhEkenzDaSCd33qrx57XZsPys64N7edjAuvScTVWa
vCj5JQcrJZV+YxTItSlrXbx4P5sqSOjg551FR8p1gFiTRyGzUaOb01TWAIovTAnz
zp9ZJZe0v3F07cSj+Ipv0JI=
-----END PRIVATE KEY-----"""
client_email = "garmin-app-writer@garminuserdata.iam.gserviceaccount.com"
client_id = "100997487695992770007"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/garmin-app-writer%40garminuserdata.iam.gserviceaccount.com"
universe_domain = "googleapis.com"